import json
from pathlib import Path

strings = {
  "en": {
    "brand": "SPANDAN AI",
    "subtitle": "Autonomous Civic Grievance Redressal",
    "heroTitle": "Tell us what went wrong. We'll help take your complaint forward.",
    "placeholder": "Tell us what happened...",
    "speak": "Speak your complaint",
    "listening": "Listening... speak naturally",
    "detecting": "Detecting language...",
    "detected": "English detected",
    "language": "Language",
    "autoDetect": "Auto Detect",
    "locationLabel": "Where is the problem?",
    "locationPlaceholder": "Area, landmark or street name",
    "submit": "Submit Complaint",
    "howItWorks": "How it works",
    "step1": "01 Tell us",
    "step2": "02 SPANDAN understands",
    "step3": "03 We file it",
    "step4": "04 SPANDAN keeps watching",
    "step5": "05 Escalate if needed",
    "trust": "Your language, your complaint, your tracking ID.",
    "navHome": "Home",
    "navComplaints": "My Complaints",
    "navActivity": "Activity",
    "navSystem": "System",
    "langName": "English"
  },
  "te": {
    "brand": "స్పందన్ AI",
    "subtitle": "స్వయంప్రతిపత్తి గల పౌర సమస్యల పరిష్కార సహాయకుడు",
    "heroTitle": "మీ సమస్య ఏమిటో స్పందన్ AI కి చెప్పండి. దాన్ని ముందుకు తీసుకెళ్లడంలో మేము మీకు సహాయం చేస్తాము.",
    "placeholder": "ఏం జరిగిందో మాకు చెప్పండి...",
    "speak": "మీ సమస్యను చెప్పండి",
    "listening": "వింటున్నాము... సహజంగా మాట్లాడండి",
    "detecting": "భాషను గుర్తిస్తున్నాము...",
    "detected": "తెలుగు గుర్తించబడింది",
    "language": "భాష",
    "autoDetect": "ఆటో డిటెక్ట్ (Auto Detect)",
    "locationLabel": "సమస్య ఎక్కడ ఉంది?",
    "locationPlaceholder": "ప్రాంతం లేదా వీధి పేరు",
    "submit": "ఫిర్యాదు పంపండి",
    "howItWorks": "ఇది ఎలా పనిచేస్తుంది",
    "step1": "01 మాకు చెప్పండి",
    "step2": "02 స్పందన్ అర్థం చేసుకుంటుంది",
    "step3": "03 మేము నమోదు చేస్తాము",
    "step4": "04 స్పందన్ పర్యవేక్షిస్తుంది",
    "step5": "05 అవసరమైతే ఉన్నతాధికారులకు పంపుతాము",
    "trust": "మీ భాష, మీ ఫిర్యాదు, మీ ట్రాకింగ్ నంబర్.",
    "navHome": "హోమ్",
    "navComplaints": "నా ఫిర్యాదులు",
    "navActivity": "కార్యాచరణ",
    "navSystem": "సిస్టమ్",
    "langName": "తెలుగు"
  },
  "ta": {
    "brand": "ஸ்பந்தன் AI",
    "subtitle": "தன்னியக்க குடிமக்கள் குறைதீர்க்கும் அமைப்பு",
    "heroTitle": "உங்கள் பிரச்சனையை சொல்லுங்கள். நாங்கள் உதவுகிறோம்.",
    "placeholder": "என்ன நடந்தது என்று சொல்லுங்கள்...",
    "speak": "உங்கள் புகாரைப் பேசுங்கள்",
    "listening": "கேட்கிறோம்... பேசுங்கள்",
    "detecting": "மொழியைக் கண்டறிகிறோம்...",
    "detected": "தமிழ் கண்டறியப்பட்டது",
    "language": "மொழி",
    "autoDetect": "தானாக கண்டறி",
    "locationLabel": "பிரச்சனை எங்கே உள்ளது?",
    "locationPlaceholder": "பகுதி அல்லது தெரு பெயர்",
    "submit": "புகாரை சமர்ப்பி",
    "howItWorks": "எப்படி செயல்படுகிறது",
    "step1": "01 எங்களிடம் கூறுங்கள்",
    "step2": "02 ஸ்பந்தன் புரிந்துகொள்ளும்",
    "step3": "03 நாங்கள் பதிவு செய்வோம்",
    "step4": "04 ஸ்பந்தன் கண்காணிக்கும்",
    "step5": "05 தேவையெனில் மேல்முறையீடு செய்யும்",
    "trust": "உங்கள் மொழி, உங்கள் புகார், உங்கள் கண்காணிப்பு எண்.",
    "navHome": "முகப்பு",
    "navComplaints": "என் புகார்கள்",
    "navActivity": "செயல்பாடுகள்",
    "navSystem": "அமைப்பு",
    "langName": "தமிழ்"
  },
  "kn": {
    "brand": "ಸ್ಪಂದನ್ AI",
    "subtitle": "ಸ್ವಾಯತ್ತ ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ನಿವಾರಣಾ ವ್ಯವಸ್ಥೆ",
    "heroTitle": "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಹೇಳಿ. ನಾವು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.",
    "placeholder": "ಏನಾಯಿತು ಎಂದು ನಮಗೆ ತಿಳಿಸಿ...",
    "speak": "ನಿಮ್ಮ ದೂರು ಮಾತನಾಡಿ",
    "listening": "ಆಲಿಸುತ್ತಿದ್ದೇವೆ... ಮಾತನಾಡಿ",
    "detecting": "ಭಾಷೆಯನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...",
    "detected": "ಕನ್ನಡ ಪತ್ತೆಯಾಗಿದೆ",
    "language": "ಭಾಷೆ",
    "autoDetect": "ಸ್ವಯಂ ಪತ್ತೆ",
    "locationLabel": "ಸಮಸ್ಯೆ ಎಲ್ಲಿದೆ?",
    "locationPlaceholder": "ಪ್ರದೇಶ ಅಥವಾ ರಸ್ತೆ ಹೆಸರು",
    "submit": "ದೂರು ಸಲ್ಲಿಸಿ",
    "howItWorks": "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    "step1": "01 ನಮಗೆ ತಿಳಿಸಿ",
    "step2": "02 ಸ್ಪಂದನ್ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತದೆ",
    "step3": "03 ನಾವು ದಾಖಲಿಸುತ್ತೇವೆ",
    "step4": "04 ಸ್ಪಂದನ್ ಗಮನಹರಿಸುತ್ತದೆ",
    "step5": "05 ಅಗತ್ಯವಿದ್ದರೆ ಮೇಲೇರಿಸುತ್ತೇವೆ",
    "trust": "ನಿಮ್ಮ ಭಾಷೆ, ನಿಮ್ಮ ದೂರು, ನಿಮ್ಮ ಟ್ರ್ಯಾಕಿಂಗ್ ಸಂಖ್ಯೆ.",
    "navHome": "ಮುಖಪುಟ",
    "navComplaints": "ನನ್ನ ದೂರುಗಳು",
    "navActivity": "ಚಟುವಟಿಕೆ",
    "navSystem": "ವ್ಯವಸ್ಥೆ",
    "langName": "ಕನ್ನಡ"
  },
  "hi": {
    "brand": "स्पंदन AI",
    "subtitle": "स्वायत्त नागरिक शिकायत निवारण",
    "heroTitle": "हमें बताएं कि क्या गलत हुआ। हम आपकी शिकायत को आगे बढ़ाने में मदद करेंगे।",
    "placeholder": "हमें बताएं कि क्या हुआ...",
    "speak": "अपनी शिकायत बोलें",
    "listening": "सुन रहे हैं... बोलिए",
    "detecting": "भाषा की पहचान हो रही है...",
    "detected": "हिन्दी पहचानी गई",
    "language": "भाषा",
    "autoDetect": "स्वतः पहचानें",
    "locationLabel": "समस्या कहाँ है?",
    "locationPlaceholder": "क्षेत्र, लैंडमार्क या सड़क का नाम",
    "submit": "शिकायत दर्ज करें",
    "howItWorks": "यह कैसे काम करता है",
    "step1": "01 हमें बताएं",
    "step2": "02 स्पंदन समझता है",
    "step3": "03 हम इसे दर्ज करते हैं",
    "step4": "04 स्पंदन नज़र रखता है",
    "step5": "05 यदि आवश्यक हो तो आगे बढ़ाएं",
    "trust": "आपकी भाषा, आपकी शिकायत, आपकी ट्रैकिंग आईडी।",
    "navHome": "होम",
    "navComplaints": "मेरी शिकायतें",
    "navActivity": "गतिविधि",
    "navSystem": "सिस्टम",
    "langName": "हिन्दी"
  }
}

target = Path("frontend/src/i18n/homeStrings.ts")
ts_content = f"""export const spandanStrings: Record<string, Record<string, string>> = {json.dumps(strings, ensure_ascii=False, indent=2)};

export function useTranslations(lang: string) {{
  return spandanStrings[lang] || spandanStrings['en'];
}}
"""

target.write_text(ts_content, encoding="utf-8")
print(f"Generated clean UTF-8 {target}")
